# Config file for the Purge plugin #
messages:
  purge_starting: 'The Purge is starting in %time% seconds!'
  purge_started_large: 'The purge has started!'
  purge_ended_large: 'The purge has ended!'
  purge_started_small: 'All PvP is now legal'
  purge_ended_small: 'PvP is disabled again'
  kill_message: '&a&l+1 kill!'
  time_left: '&c&lThe purge ends in %time% seconds!'
  no_purge: '&c&lThere is no purge going on right now.'

scoreboard:
  lines:
  - '&c&lAll PvP is currently legal!'
  - '&f'
  - '&b'
  - '&c&lHighest scores:'
  - '&4'
  - '&6&l%player1%: %score1% kills'
  - '&6&l%player2%: %score2% kills'
  - '&6&l%player3%: %score3% kills'
  - '&c'
  - '&9'
  - '&3&lYour score: %selfScore% kills'